# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/distance_calculator_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'proto/distance_calculator_service.proto\x12\x12\x64istancecalculator\x1a\x1cgoogle/protobuf/struct.proto\"h\n\x18\x43\x61lculateDistanceRequest\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x17\n\x0fsearch_distance\x18\x03 \x01(\x01\x12\x0e\n\x06object\x18\x04 \x01(\t\"O\n\x19\x43\x61lculateDistanceResponse\x12\x10\n\x08is_found\x18\x01 \x01(\x08\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\x12\x0e\n\x06object\x18\x03 \x01(\t2\x8f\x01\n\x19\x44istanceCalculatorService\x12r\n\x11\x43\x61lculateDistance\x12,.distancecalculator.CalculateDistanceRequest\x1a-.distancecalculator.CalculateDistanceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.distance_calculator_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCULATEDISTANCEREQUEST']._serialized_start=93
  _globals['_CALCULATEDISTANCEREQUEST']._serialized_end=197
  _globals['_CALCULATEDISTANCERESPONSE']._serialized_start=199
  _globals['_CALCULATEDISTANCERESPONSE']._serialized_end=278
  _globals['_DISTANCECALCULATORSERVICE']._serialized_start=281
  _globals['_DISTANCECALCULATORSERVICE']._serialized_end=424
# @@protoc_insertion_point(module_scope)
